### ISSUE TITLE
website refresh after clicking on buttons

### ISSUE THREAD

**Issue by Muphet** [im4aLL/easyeditor#1]
i have added easyeditor to my website since it was minimalistic and actually could load angularjs content i had imported to a certain div. the thing is, whenever i click any of the buttons, website refreshes.

it might be hard to present code, website is pretty complex

**Comment by im4aLL** [comment]
Okay, let me know some more details. I am assuming you are loading your whole HTML by angular route. Is it? 

or it will be very helpful if you can possibly replicate a demo. Like create a blank page and load it exactly how you are loading in your website and initialize it. 

or for quick turn around - 

Actually i am still working with easyeditor. You can try search in easyeditor.js

and Search for

``` js
_this.$toolbarContainer.find('.toolbar-'+ settings.buttonIdentifier).click(settings.clickHandler);
```

This line should be inside EasyEditor.prototype.injectButton

replace it by 

``` js
$('html').delegate('.toolbar-'+ settings.buttonIdentifier, 'click', settings.clickHandler);
```

**Comment by im4aLL** [comment]
Hi Muphet,

Yes, i've sort out the bug and added fix. Also added a demo to how to use it with form [http://habibhadi.com/lab/easyeditor/implementation-in-form.html](http://habibhadi.com/lab/easyeditor/implementation-in-form.html) 

Please download the latest JS and close issue if it's resolved!

Thanks
Hadi
