### ISSUE TITLE
Link input repeats itself

### ISSUE THREAD

**Issue by idansh** [im4aLL/easyeditor#3]
When I try to insert a link, the alert dialog opens up, I put a link and press  the button - the same alert opens again. It happens three times even if I cancel it.

Update: it can happen more times. I thinks it delegates the same as the other issue i reported.

TIP:  I think it would be better to make the prompt window not an alert, but a div that stick to the top of the text editor area (position:absolute) and upon save it closes up, better for mobile devices.

**Comment by im4aLL** [comment]
Please pull the latest updated JS once again. Issue should be fixed. Yes, for link it will be better to have a modal like http://habibhadi.com/lab/easyeditor/upload-insert-image.html (see image button)

You can enhance yours by added a popup, to overwrite default button settings http://habibhadi.com/lab/easyeditor/overwrite-button-settings.html 

Let me know if the issue still remains.

**Comment by im4aLL** [comment]
Is that issue still remains?

**Comment by idansh** [comment]
I'm pulling it now, I'll report after testing. Thanks
