### ISSUE TITLE
Edit HTML

### ISSUE THREAD

**Issue by idansh** [im4aLL/easyeditor#4]
How can I put editable HTML in the editor. I tried putting HTML (e.g. link) in the textarea, and although it is rendered as link, I can't edit it nor remove it. I need it because I am making an edit window and using it to edit a chosen HTML text. So I need to be able ti import the HTML and edit it.

How can I do that?

Thanks in advance.

**Comment by im4aLL** [comment]
Desired functionality isn't present at this moment. But i'll update plugin and will let you know :) Sorry for the inconvenience.

**Comment by im4aLL** [comment]
Hey dude, please pull the lastest JS and CSS and see demo here [source] button http://habibhadi.com/lab/easyeditor/implementation-in-form.html
