### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by linckosz** [im4aLL/easyeditor#5]
Hi,

http://stackoverflow.com/questions/18665830/getting-the-class-attribute-works-in-ie9-but-not-ie8

IE8 does bug when we try to use class as an attribute of an object, the solution is to use it explicitly as a string.
class: ..., => 'class': ...,
node.class => node['class']

Regards,

**Comment by im4aLL** [comment]
Sorry for the late response. I know it's a long time. I hope today IE8 doesn't exist! :)
